/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Map;

import java.awt.Color;
import java.net.URL;
import java.util.Timer;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author HPpro1
 */
public class Pokemon_found extends javax.swing.JFrame {

    /**
     * Creates new form Pokemon_found
     */
    public Pokemon_found() {
        initComponents();
       // World_Map.Poke_b.setBackground(Color.red);
        try{
        URL url = new URL("file:///C:/Users/HPpro1/Documents/Files/My Programs/Pokemon Atlas/New folder/Big_magmar.gif");
        Icon pokemon = new ImageIcon(url);
        URL url2 = new URL("file:///C:/Users/HPpro1/Documents/Files/My Programs/Pokemon Atlas/New folder/volcano.gif");
        Icon landmark = new ImageIcon(url2);
        
        scenario.setIcon(landmark);
        poke_img.setIcon(pokemon);
        
        
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Poke_window = new javax.swing.JPanel();
        poke_img = new javax.swing.JLabel();
        scenario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLocation(new java.awt.Point(600, 100));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Poke_window.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Poke_window.setLayout(new javax.swing.OverlayLayout(Poke_window));

        poke_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poke_window.add(poke_img);

        scenario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poke_window.add(scenario);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Pokemon GB", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\nWild Magmar has appeared!");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(Poke_window, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Poke_window, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Poke_window;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel poke_img;
    private javax.swing.JLabel scenario;
    // End of variables declaration//GEN-END:variables
}
