/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Map;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.imgscalr.Scalr;

/**
 *
 * @author HPpro1
 */
public class World_Map extends javax.swing.JFrame {

    /**
     * Creates new form World_Map
     */
    boolean flag = false;
    File img_f;
    BufferedImage image, image_r;
    int h, w, real_h, real_w;
    ImageIcon imageIcon;
    int notches;
    Point anchorPoint;
    static String gongFile;
    Cursor draggingCursor = Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR);
   // Map_label.setToolTipText("<html><img src=\"" + "file:///C:/Users/HPpro1/Downloads/New folder/imagen.jpg" + "\"> <br> MDF ED");
    Clip clip;
    
    
    public World_Map() {
         try
        {
            // the line that reads the image file
            img_f = new File("C:/Users/HPpro1/Documents/Files/My Programs/Pokemon Atlas/New folder/inProcess2.jpg");
           
            image = ImageIO.read(img_f);
            real_w = image.getWidth();
            real_h = image.getHeight();
            w = image.getWidth()/8;
            h = image.getHeight()/8;
            image_r = Scalr.resize(image, Scalr.Method.AUTOMATIC, w, h);
            imageIcon = new ImageIcon(image_r);
            visor.append("Real Width: " + real_w + " Real Height: " + real_h);
            
        }catch(Exception E){
            
     }
         
         
        initComponents();
       
        //Play music
        try{
        AudioInputStream inputStream = AudioSystem.getAudioInputStream(new File("C:/Users/HPpro1/Documents/Files/My Programs/Pokemon Atlas/New folder/theme.wav"));
        clip = AudioSystem.getClip();
        clip.open(inputStream);
        clip.loop(Clip.LOOP_CONTINUOUSLY);
       // Thread.sleep(50000);
         
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        Map_label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        coor = new javax.swing.JTextArea();
        X_coor = new javax.swing.JTextField();
        Y_coor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cir = new javax.swing.JButton();
        Poke_b = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        city = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrip = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Mute = new javax.swing.JMenuItem();
        playMusic = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo2.gif"))); // NOI18N

        Search.setText("Find Location");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        scroll.setBackground(new java.awt.Color(0, 0, 0));
        scroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Map_label.setBackground(new java.awt.Color(0, 0, 0));
        Map_label.setForeground(new java.awt.Color(255, 255, 255));
        Map_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map_label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Map_label.setIcon(imageIcon);
        Map_label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Map_labelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Map_labelMouseMoved(evt);
            }
        });
        Map_label.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                Map_labelMouseWheelMoved(evt);
            }
        });
        scroll.setViewportView(Map_label);

        jScrollPane2.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/icons/pokeball2.png")))); // NOI18N

        visor.setBackground(new java.awt.Color(204, 204, 204));
        visor.setColumns(20);
        visor.setFont(new java.awt.Font("Pokemon GB", 0, 12)); // NOI18N
        visor.setLineWrap(true);
        visor.setRows(5);
        jScrollPane2.setViewportView(visor);

        coor.setBackground(new java.awt.Color(51, 51, 51));
        coor.setColumns(20);
        coor.setFont(new java.awt.Font("Pokemon GB", 0, 8)); // NOI18N
        coor.setForeground(new java.awt.Color(0, 153, 51));
        coor.setRows(5);
        jScrollPane3.setViewportView(coor);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Y:");

        Cir.setText("Battle");
        Cir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirActionPerformed(evt);
            }
        });

        Poke_b.setText("Poke");
        Poke_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poke_bActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/City_map.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 172, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(city, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE)
        );

        descrip.setBackground(new java.awt.Color(204, 204, 204));
        descrip.setColumns(20);
        descrip.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        descrip.setRows(5);
        jScrollPane1.setViewportView(descrip);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Y_coor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Poke_b, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(X_coor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cir))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Cir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Poke_b)
                                .addGap(10, 10, 10)
                                .addComponent(Search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(X_coor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Y_coor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(527, 527, 527))))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setBorder(null);

        Menu.setText("File");

        Mute.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        Mute.setText("Mute");
        Mute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuteActionPerformed(evt);
            }
        });
        Menu.add(Mute);

        playMusic.setText("Start music");
        playMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playMusicActionPerformed(evt);
            }
        });
        Menu.add(playMusic);

        jMenuBar1.add(Menu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        int exis = Integer.parseInt(X_coor.getText());
        int eyes = Integer.parseInt(Y_coor.getText());
        
        Point position = new Point(540 - exis, 250 - eyes);
        Map_label.setBounds(position.x, position.y, Map_label.getWidth(), Map_label.getHeight());
        
    }//GEN-LAST:event_SearchActionPerformed

    private void Map_labelMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_Map_labelMouseWheelMoved
        
        
       Point mouseOnScreen = evt.getPoint();
       notches = evt.getWheelRotation();
       if (notches < 0 && w < 12000) {
           visor.append("Mouse wheel moved UP " + -notches + " notch(es)\n");
             w += 900;
             h += 900;
      
             
         if(w < 12000){    
        image_r = Scalr.resize(image, Scalr.Method.AUTOMATIC, w, h );
        imageIcon = new ImageIcon(image_r);
        Map_label.setIcon(imageIcon);
        
        Point parentOnScreen = scroll.getLocationOnScreen();
        
        Point position = new Point(parentOnScreen.x - mouseOnScreen.x, parentOnScreen.y - mouseOnScreen.y);
        Map_label.setBounds(position.x, position.y, Map_label.getWidth(), Map_label.getHeight());
        Map_label.repaint();
       }
        visor.append("width: " + w + " height: " + h + "\n");
        
       } else 
       {
          visor.append("Mouse wheel moved DOWN "  + notches + " notch(es)\n");
             w -= 900;
             h -= 900;
      
        if(w >= (real_w/8) || h >= (real_h/8)){
        image_r = Scalr.resize(image, Scalr.Method.AUTOMATIC, w, h);
        imageIcon = new ImageIcon(image_r);
        Map_label.setIcon(imageIcon);
        Map_label.repaint();
        visor.append("width: " + w + " height: " + h + "\n");
        }
        else{
            w = real_w/8;
            h = real_h/8;
        }
       }
      
       
    }//GEN-LAST:event_Map_labelMouseWheelMoved

    private void Map_labelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Map_labelMouseDragged
        // TODO add your handling code here:
     //   setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        int anchorX = anchorPoint.x;
        int anchorY = anchorPoint.y;
        
        Point parentOnScreen = scroll.getLocation();
        Point mouseOnScreen = evt.getLocationOnScreen();
        Point position = new Point(mouseOnScreen.x - parentOnScreen.x -  anchorX, mouseOnScreen.y -  parentOnScreen.y -  anchorY);
        
        if(w > real_w/8 && h > real_h/8){
            Map_label.setBounds(position.x, position.y, Map_label.getWidth(), Map_label.getHeight());
            Map_label.repaint();
        }
        
        if((w >= 9000) && (h >= 8500) && (anchorX >= 6000) && (anchorY >= 2300) ){
          
            city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Saffron_city.jpg")));
            city.repaint();
            descrip.setText(" Saffron City\n Population: 13200\n Mayor: Gary Oak\n Region: Kanto\n Gym Leader: Sabrina\n");
        }
        
        
    }//GEN-LAST:event_Map_labelMouseDragged

    private void Map_labelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Map_labelMouseMoved
        // TODO add your handling code here:
        anchorPoint = evt.getPoint();
        setCursor(Cursor.getDefaultCursor());
        coor.setText("X: " + anchorPoint.x + " Y: " + anchorPoint.y + "\n");
        if(anchorPoint.x > 2000 ){
            Poke_b.setBackground(Color.blue);
            flag = true;
        }
        
        
    }//GEN-LAST:event_Map_labelMouseMoved

    private void CirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirActionPerformed

        Battle ba = new Battle();
        ba.setVisible(true);
    }//GEN-LAST:event_CirActionPerformed

    private void MuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuteActionPerformed
        // TODO add your handling code here:
        clip.stop();
    }//GEN-LAST:event_MuteActionPerformed

    private void playMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playMusicActionPerformed
        // TODO add your handling code here:
        clip.loop(Clip.LOOP_CONTINUOUSLY);
    }//GEN-LAST:event_playMusicActionPerformed

    private void Poke_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poke_bActionPerformed
        // TODO add your handling code here:
        Pokemon_found poke = new Pokemon_found();
        poke.setVisible(true);
    }//GEN-LAST:event_Poke_bActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(World_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(World_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(World_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(World_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
              new World_Map().setVisible(true);  
             
            }  
        });
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cir;
    public static javax.swing.JLabel Map_label;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem Mute;
    public static javax.swing.JButton Poke_b;
    private javax.swing.JButton Search;
    private javax.swing.JTextField X_coor;
    private javax.swing.JTextField Y_coor;
    public static javax.swing.JLabel city;
    private javax.swing.JTextArea coor;
    private javax.swing.JTextArea descrip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem playMusic;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea visor;
    // End of variables declaration//GEN-END:variables
}
